def on_forever():
    music.set_tempo(180)
    music.set_tempo(165)
    music.play_tone(196, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(392, music.beat(BeatFraction.HALF))
    music.play_tone(523, music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.HALF))
    music.play_tone(784, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    for index in range(1):
        music.play_tone(208, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(311, music.beat(BeatFraction.HALF))
        music.play_tone(415, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(622, music.beat(BeatFraction.HALF))
        music.play_tone(831, music.beat(BeatFraction.WHOLE))
        music.play_tone(622, music.beat(BeatFraction.WHOLE))
    for index2 in range(1):
        music.play_tone(233, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(466, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(932, music.beat(BeatFraction.WHOLE))
        music.play_tone(932, music.beat(BeatFraction.HALF))
        music.play_tone(932, music.beat(BeatFraction.HALF))
        music.play_tone(932, music.beat(BeatFraction.HALF))
        music.play_tone(1046, music.beat(BeatFraction.DOUBLE))
basic.forever(on_forever)
